services:
    _defaults:
        autowire: true
        autoconfigure: true

    Everblocklight\Tools\Controller\Admin\EverblocklightAdminController:
        public: true
        arguments:
            $translator: '@translator'
        tags:
            - { name: controller.service_arguments }

    Everblocklight\Tools\Form\BlockType:
        tags: [form.type]
    Everblocklight\Tools\Form\EverblocklightConfigurationType:
        tags: [form.type]
    Everblocklight\Tools\Form\ShortcodeType:
        tags: [form.type]
    Everblocklight\Tools\Form\HookType:
        tags: [form.type]

    Everblocklight\Tools\Grid\AdminSectionGridFactory: ~

    Everblocklight\Tools\Service\AdminConfigurationManager:
        public: true

    Everblocklight\Tools\Repository\BlockRepository:
        public: true
        arguments: ['@doctrine.dbal.default_connection', '%database_prefix%']
    everblocklight.repository.block:
        alias: Everblocklight\Tools\Repository\BlockRepository
        public: true

    Everblocklight\Tools\Repository\ShortcodeRepository:
        public: true
        arguments: ['@doctrine.dbal.default_connection', '%database_prefix%']
    everblocklight.repository.shortcode:
        alias: Everblocklight\Tools\Repository\ShortcodeRepository
        public: true

    Everblocklight\Tools\Repository\HookRepository:
        public: true
        arguments: ['@doctrine.dbal.default_connection', '%database_prefix%']
    everblocklight.repository.hook:
        alias: Everblocklight\Tools\Repository\HookRepository
        public: true

    Everblocklight\Tools\Handler\ListAdminItemsHandler:
        tags:
            - { name: tactician.handler, command: Everblocklight\Tools\Query\ListAdminItemsQuery }
            - { name: messenger.message_handler, handles: Everblocklight\Tools\Query\ListAdminItemsQuery }
    Everblocklight\Tools\Handler\GetAdminItemHandler:
        tags:
            - { name: tactician.handler, command: Everblocklight\Tools\Query\GetAdminItemQuery }
            - { name: messenger.message_handler, handles: Everblocklight\Tools\Query\GetAdminItemQuery }
    Everblocklight\Tools\Handler\SaveAdminItemHandler:
        tags:
            - { name: tactician.handler, command: Everblocklight\Tools\Command\SaveAdminItemCommand }
            - { name: messenger.message_handler, handles: Everblocklight\Tools\Command\SaveAdminItemCommand }
    Everblocklight\Tools\Handler\DeleteAdminItemHandler:
        tags:
            - { name: tactician.handler, command: Everblocklight\Tools\Command\DeleteAdminItemCommand }
            - { name: messenger.message_handler, handles: Everblocklight\Tools\Command\DeleteAdminItemCommand }
    Everblocklight\Tools\Handler\ClearEverblocklightCacheHandler:
        tags:
            - { name: tactician.handler, command: Everblocklight\Tools\Command\ClearEverblocklightCacheCommand }
            - { name: messenger.message_handler, handles: Everblocklight\Tools\Command\ClearEverblocklightCacheCommand }

    everblocklight.tools.execute_action:
        class: Everblocklight\Tools\Command\ExecuteAction
        public: true
        tags:
            - { name: console.command }
